name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Docker setup
      run: |
        docker version
        sudo mkdir $HOME/.docker
        sudo touch $HOME/.docker/config.json
        echo '{"experimental":true}' | sudo $HOME/.docker/config.json
        echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        cat /etc/docker/daemon.json
    - name: Docker version
      run: |
        docker version
    - name: Docker version
      run: |
        docker manifest --help
    - name: Set env variables for Docker builds
      run: |
        echo "::set-env name=VERSION::1.0"
        echo "::set-env name=DOCKERHUB_REPO::myrepo"
    - name: Use env variables
      env:
        IMG_TAG: ${{ env.DOCKERHUB_REPO }}/appv1:${{ env.VERSION }}
      run: |
        echo $DOCKERHUB_REPO
        echo $VERSION
        echo $IMG_TAG
    - name: Use env variables again
      env:
        IMG_TAG: ${{ env.DOCKERHUB_REPO }}/appv2:${{ env.VERSION }}
      run: |
        echo $DOCKERHUB_REPO
        echo $VERSION
        echo $IMG_TAG
